// Mocks generated by Mockito 5.4.6 from annotations
// in dream_messenger_demo/integration_test/app_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:dream_messenger_demo/core/failure/failure.dart' as _i5;
import 'package:dream_messenger_demo/features/auth/domain/entities/auth_user_entity.dart'
    as _i6;
import 'package:dream_messenger_demo/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> signUp(
    _i6.AuthUserEntity? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [entity]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#signUp, [entity]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>(
                    this,
                    Invocation.method(#signUp, [entity]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> signIn(
    _i6.AuthUserEntity? entity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [entity]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
              _FakeEither_0<_i5.Failure, String>(
                this,
                Invocation.method(#signIn, [entity]),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, String>>.value(
                  _FakeEither_0<_i5.Failure, String>(
                    this,
                    Invocation.method(#signIn, [entity]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> updateUserStatus({
    required bool? setToOnline,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserStatus, [], {
              #setToOnline: setToOnline,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
              _FakeEither_0<_i5.Failure, _i2.Unit>(
                this,
                Invocation.method(#updateUserStatus, [], {
                  #setToOnline: setToOnline,
                }),
              ),
            ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i5.Failure, _i2.Unit>(
                    this,
                    Invocation.method(#updateUserStatus, [], {
                      #setToOnline: setToOnline,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
