// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDL7F8Qwp6X42J5XRACQvEH5kTAdLclOsY',
    appId: '1:288225221102:web:f9bf6fa41d6804b90196ff',
    messagingSenderId: '288225221102',
    projectId: 'dream-demo-5afa7',
    authDomain: 'dream-demo-5afa7.firebaseapp.com',
    storageBucket: 'dream-demo-5afa7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwh82hLam5-qvvyzW_soOe3AGVBJZalPI',
    appId: '1:288225221102:android:80fb857977e676e60196ff',
    messagingSenderId: '288225221102',
    projectId: 'dream-demo-5afa7',
    storageBucket: 'dream-demo-5afa7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDL7F8Qwp6X42J5XRACQvEH5kTAdLclOsY',
    appId: '1:288225221102:web:187b0daa68e817110196ff',
    messagingSenderId: '288225221102',
    projectId: 'dream-demo-5afa7',
    authDomain: 'dream-demo-5afa7.firebaseapp.com',
    storageBucket: 'dream-demo-5afa7.firebasestorage.app',
  );
}
