// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLAgDjxZK-AfWAt-qIclSTTv-5Wqx0YGs',
    appId: '1:250597604216:web:0499d66f9aaeb25c66268d',
    messagingSenderId: '250597604216',
    projectId: 'dream-demo-78152',
    authDomain: 'dream-demo-78152.firebaseapp.com',
    storageBucket: 'dream-demo-78152.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpws33cS4_KBvxpxJJD9KRN-04S0LqfQU',
    appId: '1:250597604216:android:082aafc311b7292066268d',
    messagingSenderId: '250597604216',
    projectId: 'dream-demo-78152',
    storageBucket: 'dream-demo-78152.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeJtb1F1qJ8RG_KyV_IILelY5OGeAGCks',
    appId: '1:250597604216:ios:970550cb3e05dafa66268d',
    messagingSenderId: '250597604216',
    projectId: 'dream-demo-78152',
    storageBucket: 'dream-demo-78152.firebasestorage.app',
    iosBundleId: 'com.example.dreamMessengerDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeJtb1F1qJ8RG_KyV_IILelY5OGeAGCks',
    appId: '1:250597604216:ios:970550cb3e05dafa66268d',
    messagingSenderId: '250597604216',
    projectId: 'dream-demo-78152',
    storageBucket: 'dream-demo-78152.firebasestorage.app',
    iosBundleId: 'com.example.dreamMessengerDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLAgDjxZK-AfWAt-qIclSTTv-5Wqx0YGs',
    appId: '1:250597604216:web:0b73adfb27b6d41166268d',
    messagingSenderId: '250597604216',
    projectId: 'dream-demo-78152',
    authDomain: 'dream-demo-78152.firebaseapp.com',
    storageBucket: 'dream-demo-78152.firebasestorage.app',
  );
}
